In [1]:
# %%
# Cell 0. Discover all generated size-16 cases from earlier runs, for all generated case/model folders

from pathlib import Path

ROOT = Path("..").resolve()

MODEL_SPECS = [
    {
        "model_label": "resnet50_geirhos_tl",
        "onnx_path": ROOT / "data" / "model_midlayer" / "resnet50_geirhos_tl_with_midmaps.onnx",
    },
    {
        "model_label": "resnet50_tl_20250829",
        "onnx_path": ROOT / "data" / "model_midlayer" / "resnet50_tl_20250829_with_midmaps.onnx",
    },
]

MODEL_SPEC_BY_LABEL = {m["model_label"]: m for m in MODEL_SPECS}

for spec in MODEL_SPECS:
    assert spec["onnx_path"].exists(), f"Missing ONNX model: {spec['onnx_path']}"

print("Available evaluation models:", sorted(MODEL_SPEC_BY_LABEL))

CLASS_NAMES_JSONL = ROOT / "data" / "class_names.jsonl"
assert CLASS_NAMES_JSONL.exists(), f"Missing class_names.jsonl: {CLASS_NAMES_JSONL}"

for spec in MODEL_SPECS:
    assert spec["onnx_path"].exists(), f"Missing ONNX model: {spec['onnx_path']}"

GENERATED_ROOT = ROOT / "data" / "cases" / "generated_from_best_occluders"
OUT_DIR = ROOT / "results"
OUT_DIR.mkdir(parents=True, exist_ok=True)

TARGET_SIZE = 8

def discover_generated_cases(root: Path, target_size: int = 16):
    cases = []

    for case_dir in sorted(root.iterdir()):
        if not case_dir.is_dir():
            continue

        case_id = case_dir.name

        for source_model_dir in sorted(case_dir.iterdir()):
            if not source_model_dir.is_dir():
                continue

            source_model_type = source_model_dir.name
            size_dir = source_model_dir / f"size_{target_size}"
            gen_dir = size_dir / "generated"

            paths = {
                "case_id": case_id,
                "source_model_type": source_model_type,
                "occluder_size": target_size,
                "case_dir": size_dir,
                "gen_dir": gen_dir,
                "source_config_json": gen_dir / "source_occluder_config.json",
                "occluded_png": size_dir / "occluded.png",
                "gt_png": size_dir / "gt.png",
                "shapes_xy_npz": gen_dir / "shapes_xy.npz",
                "completions_dir": gen_dir / "completions",
                "shapes_meta_jsonl": gen_dir / "shapes_meta.jsonl",
            }

            required = [
                "source_config_json",
                "occluded_png",
                "gt_png",
                "shapes_xy_npz",
                "completions_dir",
            ]

            ok = True
            for k in required:
                if not paths[k].exists():
                    print(f"Missing {k} for {case_id} | {source_model_type}:", paths[k])
                    ok = False

            if ok:
                cases.append(paths)

    return cases


cases = discover_generated_cases(GENERATED_ROOT, target_size=TARGET_SIZE)

print("Generated root:", GENERATED_ROOT)
print("Target size   :", TARGET_SIZE)
print("Cases ready   :", len(cases))
print("Source model folders found:", sorted({c['source_model_type'] for c in cases}))
print("Processing ONNX models    :", [m["model_label"] for m in MODEL_SPECS])

Available evaluation models: ['resnet50_geirhos_tl', 'resnet50_tl_20250829']
Missing source_config_json for ns_dog_780 | resnet50_tl_20250829: /data/storage-occ-v2/repos/monte-carlo-selection/data/cases/generated_from_best_occluders/ns_dog_780/resnet50_tl_20250829/size_8/generated/source_occluder_config.json
Missing shapes_xy_npz for ns_dog_780 | resnet50_tl_20250829: /data/storage-occ-v2/repos/monte-carlo-selection/data/cases/generated_from_best_occluders/ns_dog_780/resnet50_tl_20250829/size_8/generated/shapes_xy.npz
Generated root: /data/storage-occ-v2/repos/monte-carlo-selection/data/cases/generated_from_best_occluders
Target size   : 8
Cases ready   : 79
Source model folders found: ['resnet50_geirhos_tl', 'resnet50_tl_20250829']
Processing ONNX models    : ['resnet50_geirhos_tl', 'resnet50_tl_20250829']

In [2]:
# %%
# Cell 1. Load class names

import json

with CLASS_NAMES_JSONL.open("r", encoding="utf-8") as f:
    classes = [json.loads(line)["class_name"] for line in f if line.strip()]

print("Loaded class list:", len(classes))
print("First 10 classes:", classes[:10])

Loaded class list: 54
First 10 classes: ['ant', 'bat', 'bear', 'bee', 'beetle', 'bird', 'bug', 'bull', 'butterfly', 'camel']

In [3]:
# %%
# Cell. Build ONNX sessions

import onnxruntime as ort
import numpy as np
from PIL import Image
from pathlib import Path

IM_SIZE = 224
MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def preprocess_png(p: str | Path) -> np.ndarray:
    img = Image.open(p).convert("RGB").resize((IM_SIZE, IM_SIZE), resample=Image.BILINEAR)
    x = np.asarray(img, dtype=np.float32) / 255.0
    x = (x - MEAN[None, None, :]) / STD[None, None, :]
    x = np.transpose(x, (2, 0, 1))[None, ...]
    return x.astype(np.float32, copy=False)

def softmax(logits: np.ndarray) -> np.ndarray:
    z = np.asarray(logits, dtype=np.float64).reshape(-1)
    z = z - np.max(z)
    e = np.exp(z)
    return e / (np.sum(e) + 1e-12)

SESSIONS = {}

for spec in MODEL_SPECS:
    so = ort.SessionOptions()
    so.intra_op_num_threads = 30
    so.inter_op_num_threads = 1

    session = ort.InferenceSession(
        str(spec["onnx_path"]),
        sess_options=so,
        providers=["CPUExecutionProvider"],
    )

    outs = [o.name for o in session.get_outputs()]
    assert "logits" in outs, f"{spec['model_label']}: missing logits"
    assert "layer2_map" in outs, f"{spec['model_label']}: missing layer2_map"
    assert "layer3_map" in outs, f"{spec['model_label']}: missing layer3_map"

    SESSIONS[spec["model_label"]] = {
        "session": session,
        "input_name": session.get_inputs()[0].name,
        "logits_name": "logits",
        "l2_name": "layer2_map",
        "l3_name": "layer3_map",
        "onnx_path": spec["onnx_path"],
    }

print("Loaded sessions:", list(SESSIONS.keys()))

Loaded sessions: ['resnet50_geirhos_tl', 'resnet50_tl_20250829']

In [4]:
# %%
# Cell 3. Model-aware inference helpers

def infer_maps_and_logits(p: str | Path, model_label: str):
    sess_info = SESSIONS[model_label]
    x = preprocess_png(p)
    l2, l3, logits = sess_info["session"].run(
        [sess_info["l2_name"], sess_info["l3_name"], sess_info["logits_name"]],
        {sess_info["input_name"]: x}
    )
    return np.asarray(l2), np.asarray(l3), np.asarray(logits).reshape(-1)

def target_from_occluded(case: dict, model_label: str):
    _, _, occ_logits = infer_maps_and_logits(case["occluded_png"], model_label=model_label)
    occ_prob = softmax(occ_logits)
    target_idx = int(np.argmax(occ_logits))
    return target_idx, float(occ_logits[target_idx]), float(occ_prob[target_idx])

In [5]:
# %%
# Cell 4. Load shapes_xy.npz for a case and resolve completion PNG paths

import numpy as np
from pathlib import Path

def load_case_shapes(case: dict):
    z = np.load(case["shapes_xy_npz"], allow_pickle=True)
    out_files_raw = z["out_files"].tolist()
    polygons_xy   = z["polygons"]
    matlab_1_indexed = bool(z["matlab_1_indexed"]) if "matlab_1_indexed" in z else False

    completions_dir = case["completions_dir"]

    def resolve_png_path(p: str) -> Path:
        pth = Path(p)
        if pth.exists():
            return pth
        return completions_dir / pth.name

    png_paths = [resolve_png_path(p) for p in out_files_raw]
    missing = sum(1 for p in png_paths if not p.exists())

    return png_paths, polygons_xy, matlab_1_indexed, missing

In [6]:
# %%
# Cell 6. Model-aware parallel scoring

from concurrent.futures import ProcessPoolExecutor, as_completed
import numpy as np
from tqdm.auto import tqdm

N_WORKERS = 60

def _score_chunk_onnx(args):
    chunk_pairs, target_idx, occ_tlog, onnx_path_str, logits_out_name = args

    import os
    import numpy as np
    import onnxruntime as ort
    from PIL import Image

    so = ort.SessionOptions()
    so.intra_op_num_threads = 1
    so.inter_op_num_threads = 1

    sess = ort.InferenceSession(onnx_path_str, sess_options=so, providers=["CPUExecutionProvider"])
    in_name = sess.get_inputs()[0].name

    IM_SIZE = 224
    MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

    def preprocess(p):
        img = Image.open(p).convert("RGB").resize((IM_SIZE, IM_SIZE), resample=Image.BILINEAR)
        x = np.asarray(img, dtype=np.float32) / 255.0
        x = (x - MEAN[None, None, :]) / STD[None, None, :]
        x = np.transpose(x, (2, 0, 1))[None, ...]
        return x.astype(np.float32, copy=False)

    def softmax_local(logits):
        z = np.asarray(logits, dtype=np.float64).reshape(-1)
        z = z - np.max(z)
        e = np.exp(z)
        return e / (np.sum(e) + 1e-12)

    idxs = []
    v_tlog = []
    v_tpr  = []
    v_tmar = []
    v_tdel = []

    for i, pstr in chunk_pairs:
        try:
            if not os.path.exists(pstr):
                continue

            x = preprocess(pstr)
            logits = sess.run([logits_out_name], {in_name: x})[0]
            logits = np.asarray(logits).reshape(-1)

            prob = softmax_local(logits)
            tl = float(logits[int(target_idx)])
            other_max = float(np.max(np.delete(logits, int(target_idx))))

            idxs.append(int(i))
            v_tlog.append(tl)
            v_tpr.append(float(prob[int(target_idx)]))
            v_tdel.append(float(tl - float(occ_tlog)))
            v_tmar.append(float(tl - other_max))
        except Exception:
            continue

    return (
        np.asarray(idxs, dtype=np.int64),
        np.asarray(v_tlog, dtype=np.float64),
        np.asarray(v_tpr, dtype=np.float64),
        np.asarray(v_tmar, dtype=np.float64),
        np.asarray(v_tdel, dtype=np.float64),
        int(len(idxs)),
    )


def score_case_parallel(case: dict, png_paths: list, target_idx: int, occ_tlog: float, model_label: str):
    N = len(png_paths)
    tlog = np.full(N, np.nan, dtype=np.float64)
    tpr  = np.full(N, np.nan, dtype=np.float64)
    tmar = np.full(N, np.nan, dtype=np.float64)
    tdel = np.full(N, np.nan, dtype=np.float64)

    pairs = [(i, str(p)) for i, p in enumerate(png_paths)]
    if len(pairs) == 0:
        print("No png_paths for case:", case.get("case_id", "unknown"))
        return tlog, tpr, tmar, tdel

    sess_info = SESSIONS[model_label]
    onnx_path = str(sess_info["onnx_path"])
    logits_name = sess_info["logits_name"]

    chunk_size = max(1, len(pairs) // (N_WORKERS * 30))
    chunks = [pairs[j:j+chunk_size] for j in range(0, len(pairs), chunk_size)]
    args_list = [(ch, target_idx, occ_tlog, onnx_path, logits_name) for ch in chunks]

    with ProcessPoolExecutor(max_workers=N_WORKERS) as ex:
        futs = [ex.submit(_score_chunk_onnx, a) for a in args_list]
        for fut in tqdm(as_completed(futs), total=len(futs), desc=f"Scoring {case.get('case_id','case')} | {model_label}"):
            idxs, a, b, c, d, _ = fut.result()
            if idxs.size:
                tlog[idxs] = a
                tpr[idxs]  = b
                tmar[idxs] = c
                tdel[idxs] = d

    return tlog, tpr, tmar, tdel

In [7]:
# %%
# Cell 7. New occluder mask builder from source_occluder_config.json

import json
import numpy as np
from PIL import Image, ImageDraw
from pathlib import Path

def build_occluder_mask_from_source_config(case: dict):
    cfg = json.loads(Path(case["source_config_json"]).read_text(encoding="utf-8"))

    x0 = float(cfg["x0_norm"])
    y0 = float(cfg["y0_norm"])
    x1 = float(cfg["x1_norm"])
    y1 = float(cfg["y1_norm"])

    W_img, H_img = Image.open(case["occluded_png"]).size

    occluder_px = np.array([
        [x0 * (W_img - 1), y0 * (H_img - 1)],
        [x1 * (W_img - 1), y0 * (H_img - 1)],
        [x1 * (W_img - 1), y1 * (H_img - 1)],
        [x0 * (W_img - 1), y1 * (H_img - 1)],
    ], dtype=np.float64)

    occ_mask_img = Image.new("L", (W_img, H_img), 0)
    draw = ImageDraw.Draw(occ_mask_img)
    draw.polygon([(float(x), float(y)) for x, y in occluder_px], outline=1, fill=1)
    occluder_mask = (np.asarray(occ_mask_img, dtype=np.uint8) > 0)

    return occluder_mask, occluder_px, (W_img, H_img)

In [8]:
# %%
# Cell 8. Batch BGMM output base

from pathlib import Path
import json

BGMM_DIR = OUT_DIR / "occlusion" / "bgmm_generated_size16_both_models"
BGMM_DIR.mkdir(parents=True, exist_ok=True)

def write_jsonl(path: Path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

print("BGMM_DIR:", BGMM_DIR)

BGMM_DIR: /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models

In [9]:
# %%
# Cell 9. Imports used by the single-case-equivalent pipeline

import numpy as np
import pandas as pd
from datetime import datetime, timezone
from PIL import Image, ImageDraw
from shapely.geometry import Point, Polygon
from sklearn.decomposition import PCA
from sklearn.mixture import BayesianGaussianMixture
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm.auto import tqdm

In [10]:
# %%
# Cell 10. Core pipeline functions

def build_eligible_set(tlog: np.ndarray, *, valid_poly=None) -> np.ndarray:
    N_total = int(tlog.shape[0])
    E = np.isfinite(tlog)

    if valid_poly is not None:
        vp = np.asarray(valid_poly, dtype=bool)
        if vp.shape[0] == N_total:
            E = E & vp
        else:
            print("Warning: valid_poly length mismatch. Skipping valid_poly filter.")

    return np.where(E)[0].astype(int)


def run_pca(Xn: np.ndarray, PCA_D: int = 30):
    pca = PCA(n_components=int(PCA_D), random_state=0)
    Z = pca.fit_transform(Xn)
    evr = np.asarray(pca.explained_variance_ratio_, dtype=np.float64)
    return Z, pca, evr


def run_bgmm(Z: np.ndarray, K_MAX: int = 80, ACTIVE_THR: float = 1e-4):
    bgmm = BayesianGaussianMixture(
        n_components=int(K_MAX),
        covariance_type="diag",
        weight_concentration_prior_type="dirichlet_process",
        weight_concentration_prior=1e-2,
        max_iter=2000,
        random_state=0,
        init_params="kmeans",
        reg_covar=1e-6,
    )
    bgmm.fit(Z)

    resp = bgmm.predict_proba(Z)
    mix_w = np.asarray(bgmm.weights_, dtype=np.float64)
    active = np.where(mix_w > float(ACTIVE_THR))[0].astype(int)
    return bgmm, resp, mix_w, active


def turning_curvature(polyline_xy: np.ndarray, eps: float = 1e-12) -> float:
    x = np.asarray(polyline_xy, dtype=np.float64)
    if x.shape[0] < 3:
        return np.nan
    v1 = x[1:-1] - x[:-2]
    v2 = x[2:]   - x[1:-1]
    n1 = np.linalg.norm(v1, axis=1) + eps
    n2 = np.linalg.norm(v2, axis=1) + eps
    v1u = v1 / n1[:, None]
    v2u = v2 / n2[:, None]
    dot = np.clip(np.sum(v1u * v2u, axis=1), -1.0, 1.0)
    cross = v1u[:, 0] * v2u[:, 1] - v1u[:, 1] * v2u[:, 0]
    ang = np.arctan2(cross, dot)
    total_turn = np.sum(np.abs(ang))
    seg = x[1:] - x[:-1]
    arc_len = float(np.sum(np.linalg.norm(seg, axis=1)))
    return float(total_turn / (arc_len + eps))


def _points_inside_occluder_xy(xy: np.ndarray, occ_poly_wkb: bytes) -> np.ndarray:
    from shapely import wkb
    from shapely.geometry import Point
    poly = wkb.loads(occ_poly_wkb)

    if xy.size == 0:
        return xy.reshape(0, 2)
    inside = []
    for p in xy:
        if poly.contains(Point(float(p[0]), float(p[1]))):
            inside.append(p)
    return np.asarray(inside, dtype=np.float64) if inside else np.zeros((0, 2), dtype=np.float64)


def _curv_one(args):
    j, i, pts, occ_poly_wkb, m1 = args
    pts = np.asarray(pts, dtype=np.float64).reshape(-1, 2)
    if m1:
        pts = pts - 1.0
    pts_in = _points_inside_occluder_xy(pts, occ_poly_wkb)
    if pts_in.shape[0] >= 3:
        c = turning_curvature(pts_in)
    else:
        c = turning_curvature(pts)
    return j, float(c)


def compute_curvatures(polygons_xy, E_idx, occluder_px, matlab_1_indexed_flag: bool, N_WORKERS: int = 60):
    occ_poly = Polygon(np.asarray(occluder_px, dtype=np.float64).tolist())
    occ_wkb = occ_poly.wkb

    tasks = [
        (j, int(i), polygons_xy[int(i)], occ_wkb, bool(matlab_1_indexed_flag))
        for j, i in enumerate(E_idx)
    ]

    curv = np.full((len(E_idx),), np.nan, dtype=np.float64)

    with ProcessPoolExecutor(max_workers=int(N_WORKERS)) as ex:
        futs = [ex.submit(_curv_one, t) for t in tasks]
        for fut in as_completed(futs):
            j, c = fut.result()
            curv[j] = c

    return curv


def _png_to_shape_mask_from_path(p_str: str) -> np.ndarray:
    arr = np.asarray(Image.open(p_str).convert("L"), dtype=np.uint8)
    return arr < 128


def _worker_chunk_fill(args):
    js, idxs, png_paths_str, occluder_mask, baseline_mask = args

    fill1 = np.full((len(js),), np.nan, dtype=np.float64)
    fill2 = np.full((len(js),), np.nan, dtype=np.float64)

    from pathlib import Path as _Path

    for k, (j, i) in enumerate(zip(js, idxs)):
        p = png_paths_str[int(i)]
        if not p:
            continue
        if not _Path(p).exists():
            continue

        m = _png_to_shape_mask_from_path(p)
        fill1[k] = float(m[occluder_mask].mean())

        added = m & (~baseline_mask)
        fill2[k] = float(added[occluder_mask].mean())

    return js, fill1, fill2


def compute_fill_metrics(
    png_paths,
    E_idx,
    occluder_mask,
    occluded_png_path,
    N_WORKERS: int = 30,
    CHUNK_SIZE: int = 150,
):
    baseline_mask = _png_to_shape_mask_from_path(str(occluded_png_path))
    png_paths_str = [str(p) for p in png_paths]

    fill_in_occ = np.full((len(E_idx),), np.nan, dtype=np.float64)
    fill_added_in_occ = np.full((len(E_idx),), np.nan, dtype=np.float64)

    chunks = []
    for start in range(0, len(E_idx), int(CHUNK_SIZE)):
        stop = min(len(E_idx), start + int(CHUNK_SIZE))
        js = list(range(start, stop))
        idxs = [int(E_idx[j]) for j in js]
        chunks.append((js, idxs, png_paths_str, occluder_mask, baseline_mask))

    with ProcessPoolExecutor(max_workers=int(N_WORKERS)) as ex:
        futs = [ex.submit(_worker_chunk_fill, c) for c in chunks]
        for fut in tqdm(as_completed(futs), total=len(futs), desc="fill metrics"):
            js, fill1, fill2 = fut.result()
            fill_in_occ[js] = fill1
            fill_added_in_occ[js] = fill2

    return fill_in_occ, fill_added_in_occ


def invfreq_weights_quantile(x: np.ndarray, bins: int) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    qs = np.linspace(0.0, 1.0, int(bins) + 1)
    edges = np.quantile(x, qs)
    edges[0] -= 1e-12
    edges[-1] += 1e-12
    b = np.digitize(x, edges) - 1
    b = np.clip(b, 0, bins - 1)
    cnt = np.bincount(b, minlength=bins).astype(np.float64)
    p = cnt / (cnt.sum() + 1e-12)
    w = 1.0 / (p[b] + 1e-12)
    w = w / (w.mean() + 1e-12)
    return w


def compute_debias_weights(curv, fill_in_occ, *, BINS_CURV=20, BINS_SIZE=20, CAP=10.0):
    size_metric = np.asarray(fill_in_occ, dtype=np.float64)

    curv_safe = np.asarray(curv, dtype=np.float64).copy()
    curv_safe[~np.isfinite(curv_safe)] = float(np.nanmedian(curv_safe))

    ok = np.isfinite(curv_safe) & np.isfinite(size_metric)
    if int(ok.sum()) < 50:
        raise RuntimeError(f"Too few valid samples for debiasing: {int(ok.sum())}")

    w_curv = np.ones((len(curv_safe),), dtype=np.float64)
    w_size = np.ones((len(curv_safe),), dtype=np.float64)

    w_curv[ok] = invfreq_weights_quantile(curv_safe[ok], bins=int(BINS_CURV))
    w_size[ok] = invfreq_weights_quantile(size_metric[ok], bins=int(BINS_SIZE))

    w_joint = w_curv * w_size
    w_joint[ok] = np.clip(w_joint[ok], 1.0 / float(CAP), float(CAP))
    w_joint[ok] = w_joint[ok] / (np.mean(w_joint[ok]) + 1e-12)

    return w_joint, ok


def build_component_table(resp, mix_w, w_joint, ACTIVE_THR=1e-4):
    resp = np.asarray(resp, dtype=np.float64)
    mix_w = np.asarray(mix_w, dtype=np.float64)
    w_joint = np.asarray(w_joint, dtype=np.float64)

    mass_raw = resp.sum(axis=0)
    mass_debias = (w_joint[:, None] * resp).sum(axis=0)

    comp_df = pd.DataFrame({
        "k": np.arange(resp.shape[1], dtype=int),
        "mix_weight": mix_w,
        "mass_raw": mass_raw,
        "mass_debias": mass_debias,
    })

    active_df = comp_df.query(f"mix_weight > {float(ACTIVE_THR)}").copy()
    active_df = active_df.sort_values("mass_debias", ascending=False).reset_index(drop=True)
    return comp_df, active_df


def export_bgmm_jsonls(
    case_id: str,
    out_base_dir,
    *,
    png_paths,
    E_idx,
    Z,
    evr,
    pca_obj,
    bgmm_obj,
    resp,
    mix_w,
    comp_df,
    active_df,
    top_clusters_n: int = 10,
    top_shapes_per_cluster: int = 25,
    ACTIVE_THR: float = 1e-4,
):
    out_base_dir = Path(out_base_dir) / case_id
    out_base_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")

    active_order = active_df["k"].astype(int).tolist()
    k_to_rank = {int(k): int(r + 1) for r, k in enumerate(active_order)}

    meta = {
        "timestamp_utc": ts,
        "case_id": case_id,
        "n_total_completions": int(len(png_paths)),
        "n_eligible": int(len(E_idx)),
        "pca_d": int(Z.shape[1]),
        "pca_cum_explained_var": float(np.sum(evr)),
        "pca_explained_var_first10": [float(x) for x in evr[:10]],
        "bgmm_k_max": int(resp.shape[1]),
        "bgmm_active_thr": float(ACTIVE_THR),
        "n_active": int(active_df.shape[0]),
        "top_clusters_n": int(top_clusters_n),
        "top_shapes_per_cluster": int(top_shapes_per_cluster),
    }
    write_jsonl(out_base_dir / "meta.jsonl", [meta])

    comp_rows = []
    for _, row in comp_df.iterrows():
        k = int(row["k"])
        comp_rows.append({
            "timestamp_utc": ts,
            "case_id": case_id,
            "k": k,
            "mix_weight": float(row["mix_weight"]),
            "mass_raw": float(row["mass_raw"]),
            "mass_debias": float(row["mass_debias"]),
            "is_active": bool(float(row["mix_weight"]) > float(ACTIVE_THR)),
            "active_rank_by_mass_debias": int(k_to_rank[k]) if k in k_to_rank else None,
        })
    write_jsonl(out_base_dir / "components.jsonl", comp_rows)

    assign_rows = []
    resp = np.asarray(resp, dtype=np.float64)
    for j, i in enumerate(E_idx):
        r = resp[j]
        k_hat = int(np.argmax(r))
        topk = np.argsort(-r)[: min(5, r.size)].astype(int)
        assign_rows.append({
            "timestamp_utc": ts,
            "case_id": case_id,
            "eligible_row": int(j),
            "global_index": int(i),
            "png": str(png_paths[int(i)]),
            "k_argmax": k_hat,
            "k_rank_among_active": int(k_to_rank[k_hat]) if k_hat in k_to_rank else None,
            "resp_top5": [{"k": int(kk), "p": float(r[int(kk)])} for kk in topk],
        })
    write_jsonl(out_base_dir / "shape_to_cluster.jsonl", assign_rows)

    top_rows = []
    top_ks = active_df.head(int(top_clusters_n))["k"].astype(int).tolist()
    for rank, k in enumerate(top_ks, start=1):
        r_k = resp[:, int(k)]
        topj = np.argsort(-r_k)[: int(top_shapes_per_cluster)].astype(int)
        shapes = []
        for jj in topj:
            gi = int(E_idx[int(jj)])
            shapes.append({
                "eligible_row": int(jj),
                "global_index": gi,
                "png": str(png_paths[gi]),
                "resp": float(r_k[int(jj)]),
            })
        top_rows.append({
            "timestamp_utc": ts,
            "case_id": case_id,
            "cluster_rank": int(rank),
            "k": int(k),
            "mix_weight": float(active_df.loc[active_df["k"] == k, "mix_weight"].iloc[0]),
            "mass_debias": float(active_df.loc[active_df["k"] == k, "mass_debias"].iloc[0]),
            "shapes": shapes,
        })
    write_jsonl(out_base_dir / "top10_clusters.jsonl", top_rows)

    params = {
        "timestamp_utc": ts,
        "case_id": case_id,
        "bgmm_weights": [float(x) for x in np.asarray(bgmm_obj.weights_, dtype=np.float64).tolist()],
        "bgmm_means": np.asarray(bgmm_obj.means_, dtype=np.float64).tolist(),
        "bgmm_covariances": np.asarray(bgmm_obj.covariances_, dtype=np.float64).tolist(),
        "bgmm_precisions_cholesky": np.asarray(bgmm_obj.precisions_cholesky_, dtype=np.float64).tolist(),
        "pca_components": np.asarray(pca_obj.components_, dtype=np.float64).tolist(),
        "pca_mean": np.asarray(pca_obj.mean_, dtype=np.float64).tolist(),
        "pca_explained_variance": np.asarray(pca_obj.explained_variance_, dtype=np.float64).tolist(),
    }
    write_jsonl(out_base_dir / "model_params.jsonl", [params])

    return out_base_dir

In [11]:
# %%
# Cell. Model-aware ROI-pooled mid-level embeddings

import numpy as np
from PIL import Image

def build_embeddings_Xn(png_paths, E_idx, occluder_mask_imgspace, model_label: str, use_contrast: bool = True):
    """
    ROI-pooled mid-level embeddings using layer2_map + layer3_map.
    Pools activations inside the occluder region, optionally using inside-minus-outside contrast.
    Returns an L2-normalized embedding matrix Xn with shape (|E|, 512+1024).
    """

    def _resize_mask(mask_img: np.ndarray, size_hw):
        H, W = int(size_hw[0]), int(size_hw[1])
        m = Image.fromarray(mask_img.astype(np.uint8) * 255)
        m = m.resize((W, H), resample=Image.NEAREST)
        return (np.asarray(m) > 0)

    def _roi_pool_map(feat_map: np.ndarray, mask_small: np.ndarray, contrast: bool):
        fmap = np.asarray(feat_map)[0]   # (C,H,W)

        inside = mask_small[None, :, :]
        outside = ~inside
        eps = 1e-6

        mean_in = (fmap * inside).sum(axis=(1, 2)) / (inside.sum(axis=(1, 2)) + eps)

        if not contrast:
            return mean_in

        mean_out = (fmap * outside).sum(axis=(1, 2)) / (outside.sum(axis=(1, 2)) + eps)
        return mean_in - mean_out

    # infer shapes from first eligible sample
    l2, l3, _ = infer_maps_and_logits(png_paths[int(E_idx[0])], model_label=model_label)

    mask_l2 = _resize_mask(occluder_mask_imgspace, l2.shape[-2:])
    mask_l3 = _resize_mask(occluder_mask_imgspace, l3.shape[-2:])

    dim = int(l2.shape[1]) + int(l3.shape[1])   # 512 + 1024
    X = np.zeros((len(E_idx), dim), dtype=np.float32)

    for j, i in enumerate(E_idx):
        l2, l3, _ = infer_maps_and_logits(png_paths[int(i)], model_label=model_label)
        v2 = _roi_pool_map(l2, mask_l2, contrast=use_contrast)
        v3 = _roi_pool_map(l3, mask_l3, contrast=use_contrast)
        X[j] = np.concatenate([v2, v3]).astype(np.float32, copy=False)

    norm = np.linalg.norm(X, axis=1, keepdims=True) + 1e-12
    return X / norm

In [12]:
# %%
# Cell. Output path helpers for source-only evaluation

from pathlib import Path

def run_output_dir(case: dict) -> Path:
    return (
        BGMM_DIR
        / f"source_{case['source_model_type']}"
        / f"size_{case['occluder_size']}"
        / case["case_id"]
    )

In [13]:
def run_already_processed(case: dict, require_all: bool = True):
    out_dir = run_output_dir(case)

    required_files = [
        out_dir / "meta.jsonl",
        out_dir / "components.jsonl",
        out_dir / "shape_to_cluster.jsonl",
        out_dir / "top10_clusters.jsonl",
        out_dir / "model_params.jsonl",
    ]

    exists = [p.exists() for p in required_files]

    if require_all:
        done = all(exists)
    else:
        done = any(exists)

    return done, out_dir, required_files

In [14]:
# %%
# Cell. Preview runs

pending_rows = []
done_rows = []

for case in cases:
    done, out_dir, required_files = run_already_processed(case, require_all=True)

    row = {
        "case_id": case["case_id"],
        "source_model_type": case["source_model_type"],
        "occluder_size": case["occluder_size"],
        "out_dir": str(out_dir),
        "already_processed": done,
    }

    if done:
        done_rows.append(row)
    else:
        pending_rows.append(row)

done_df = pd.DataFrame(done_rows)
pending_df = pd.DataFrame(pending_rows)

print("Already processed:", len(done_df))
print("Pending         :", len(pending_df))

if len(done_df):
    display(done_df.head(20))
if len(pending_df):
    display(pending_df.head(20))

Already processed: 27
Pending         : 52

,case_id,source_model_type,occluder_size,out_dir,already_processed
0,ns_cow_202,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
1,ns_cow_202,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
2,ns_cow_205,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
3,ns_cow_205,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
4,ns_cow_350,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
5,ns_cow_350,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
6,ns_cow_510,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
7,ns_cow_510,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
8,ns_cow_780,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
9,ns_cow_780,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
10,ns_dog_105,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
11,ns_dog_105,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
12,ns_dog_214,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
13,ns_dog_214,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
14,ns_dog_350,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
15,ns_dog_350,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
16,ns_dog_69,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
17,ns_dog_69,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
18,ns_dog_780,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True
19,ns_elephant_100,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,True

,case_id,source_model_type,occluder_size,out_dir,already_processed
0,ns_elephant_780,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
1,ns_elephant_780,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
2,ns_lion_350,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
3,ns_lion_350,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
4,ns_lion_560,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
5,ns_lion_560,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
6,ns_lion_650,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
7,ns_lion_650,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
8,ns_lion_780,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
9,ns_lion_780,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
10,ns_lion_801,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
11,ns_lion_801,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
12,s_bird_111,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
13,s_bird_111,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
14,s_bird_117,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
15,s_bird_117,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
16,s_bird_132,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
17,s_bird_132,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
18,s_bird_136,resnet50_geirhos_tl,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False
19,s_bird_136,resnet50_tl_20250829,8,/data/storage-occ-v2/repos/monte-carlo-selecti...,False

In [15]:
# %%
# Cell. Batch run: each source model evaluates only the shapes it generated

PCA_D = 30
K_MAX = 80
ACTIVE_THR = 1e-4

N_WORKERS = 60
FILL_CHUNK = 150

TOP_CLUSTERS_N = 10
TOP_SHAPES_PER_CLUSTER = 25

export_dirs = []
skipped_runs = []

for case in cases:
    case_id = case["case_id"]
    source_model_type = case["source_model_type"]
    eval_model_label = source_model_type

    if eval_model_label not in MODEL_SPEC_BY_LABEL:
        print(f"Skipping {case_id}: no ONNX mapping found for source model '{source_model_type}'")
        continue

    done, out_dir, required_files = run_already_processed(case, require_all=True)

    if done:
        print(
            "Skipping already processed:",
            case["case_id"],
            "| source/eval =", source_model_type,
            "| size =", case["occluder_size"],
        )
        skipped_runs.append({
            "case_id": case["case_id"],
            "source_model_type": source_model_type,
            "occluder_size": case["occluder_size"],
            "out_dir": str(out_dir),
        })
        continue

    png_paths, polygons_xy, matlab_1_indexed, missing = load_case_shapes(case)
    if missing > 0:
        print("Warning:", case_id, "|", source_model_type, "missing PNGs:", missing)

    target_idx, occ_tlog, occ_tpr = target_from_occluded(case, model_label=eval_model_label)

    tlog, tpr, tmar, tdel = score_case_parallel(
        case=case,
        png_paths=png_paths,
        target_idx=target_idx,
        occ_tlog=occ_tlog,
        model_label=eval_model_label,
    )

    E_idx = build_eligible_set(tlog)

    print("\nCASE:", case_id)
    print("  source model      :", source_model_type)
    print("  eval model        :", eval_model_label)
    print("  occluder size     :", case["occluder_size"])
    print("  Eligible          :", int(len(E_idx)), "/", int(len(png_paths)))
    print(
        "  Target            :",
        classes[target_idx],
        "idx:",
        int(target_idx),
        "occ_tlog:",
        float(occ_tlog),
        "occ_tpr:",
        float(occ_tpr),
    )

    if len(E_idx) < 50:
        print("  Skipping BGMM. Too few eligible samples.")
        continue

    occluder_mask, occluder_px, _ = build_occluder_mask_from_source_config(case)

    Xn = build_embeddings_Xn(
        png_paths=png_paths,
        E_idx=E_idx,
        occluder_mask_imgspace=occluder_mask,
        model_label=eval_model_label,
        use_contrast=True,
    )

    Z, pca_obj, evr = run_pca(Xn, PCA_D=PCA_D)
    bgmm_obj, resp, mix_w, active = run_bgmm(Z, K_MAX=K_MAX, ACTIVE_THR=ACTIVE_THR)

    print("  Z:", tuple(Z.shape), "PCA cum EV:", float(np.sum(evr)))
    print("  Active components:", int(active.size), "/", int(K_MAX))

    curv = compute_curvatures(
        polygons_xy=polygons_xy,
        E_idx=E_idx,
        occluder_px=occluder_px,
        matlab_1_indexed_flag=matlab_1_indexed,
        N_WORKERS=N_WORKERS,
    )

    fill_in_occ, fill_added_in_occ = compute_fill_metrics(
        png_paths=png_paths,
        E_idx=E_idx,
        occluder_mask=occluder_mask,
        occluded_png_path=case["occluded_png"],
        N_WORKERS=N_WORKERS,
        CHUNK_SIZE=FILL_CHUNK,
    )

    w_joint, ok = compute_debias_weights(
        curv,
        fill_in_occ,
        BINS_CURV=20,
        BINS_SIZE=20,
        CAP=10.0,
    )

    comp_df, active_df = build_component_table(resp, mix_w, w_joint, ACTIVE_THR=ACTIVE_THR)

    print("  Top-5 clusters by mass_debias:")
    print(active_df.head(5)[["k", "mix_weight", "mass_debias"]])

    out_dir_case = export_bgmm_jsonls(
        case_id=case["case_id"],
        out_base_dir=(
            BGMM_DIR
            / f"source_{source_model_type}"
            / f"size_{case['occluder_size']}"
        ),
        png_paths=png_paths,
        E_idx=E_idx,
        Z=Z,
        evr=evr,
        pca_obj=pca_obj,
        bgmm_obj=bgmm_obj,
        resp=resp,
        mix_w=mix_w,
        comp_df=comp_df,
        active_df=active_df,
        top_clusters_n=TOP_CLUSTERS_N,
        top_shapes_per_cluster=TOP_SHAPES_PER_CLUSTER,
        ACTIVE_THR=ACTIVE_THR,
    )
    export_dirs.append(str(out_dir_case))

print("\nDone. Newly exported BGMM JSONLs for runs:", len(export_dirs))
for d in export_dirs[:10]:
    print("  ", d)
if len(export_dirs) > 10:
    print("  ...")

print("\nSkipped already processed runs:", len(skipped_runs))
for r in skipped_runs[:10]:
    print("  ", r["case_id"], "|", r["source_model_type"], "| size", r["occluder_size"])
if len(skipped_runs) > 10:
    print("  ...")

Skipping already processed: ns_cow_202 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_cow_202 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_cow_205 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_cow_205 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_cow_350 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_cow_350 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_cow_510 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_cow_510 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_cow_780 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_cow_780 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_dog_105 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_dog_105 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_dog_214 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_dog_214 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_dog_350 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_dog_350 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_dog_69 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_dog_69 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_dog_780 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_elephant_100 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_elephant_100 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_elephant_109 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_elephant_109 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_elephant_350 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_elephant_350 | source/eval = resnet50_tl_20250829 | size = 8
Skipping already processed: ns_elephant_47 | source/eval = resnet50_geirhos_tl | size = 8
Skipping already processed: ns_elephant_47 | source/eval = resnet50_tl_20250829 | size = 8

Scoring ns_elephant_780 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_elephant_780
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : sheep idx: 42 occ_tlog: 4.627476692199707 occ_tpr: 0.2015942161172042

  Z: (10000, 30) PCA cum EV: 0.9832615877967328
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   0    0.016492   163.952402
1   8    0.016469   163.862515
2  11    0.016460   163.825929
3  18    0.016436   163.733679
4  24    0.016414   163.645616

Scoring ns_elephant_780 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_elephant_780
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 130.43707275390625 occ_tpr: 0.9999912994424993

  Z: (10000, 30) PCA cum EV: 0.9940140317485202
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.721807
1  1    0.012669   125.712704
2  2    0.012667   125.703104
3  3    0.012664   125.693445
4  4    0.012662   125.684005

Scoring ns_lion_350 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_350
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : squirrel idx: 46 occ_tlog: 3.5574843883514404 occ_tpr: 0.22660629538969607

  Z: (10000, 30) PCA cum EV: 0.9811290199868381
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  12    0.032633   325.787330
1  18    0.026357   263.140473
2  47    0.025999   260.933320
3  28    0.019572   195.435241
4  32    0.019551   195.351343

Scoring ns_lion_350 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_350
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 119.88497161865234 occ_tpr: 0.9995045207296684

  Z: (10000, 30) PCA cum EV: 0.9956629249936668
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.720959
1  1    0.012669   125.711664
2  2    0.012666   125.702315
3  3    0.012664   125.692960
4  4    0.012662   125.683529

Scoring ns_lion_560 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_560
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : lion idx: 30 occ_tlog: 4.359492778778076 occ_tpr: 0.1924803185004763

  Z: (10000, 30) PCA cum EV: 0.9703897932195105
  Active components: 79 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   7    0.049525   494.652747
1  39    0.039731   398.674751
2  52    0.027971   281.352556
3   5    0.026556   264.710860
4  29    0.026175   261.788777

Scoring ns_lion_560 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_560
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 129.54762268066406 occ_tpr: 0.9999999991190289

  Z: (10000, 30) PCA cum EV: 0.9957552804553416
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012672   125.729577
1  1    0.012669   125.720041
2  2    0.012667   125.710768
3  3    0.012665   125.700272
4  4    0.012662   125.691952

Scoring ns_lion_650 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_650
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : lion idx: 30 occ_tlog: 3.701479196548462 occ_tpr: 0.11893198443333357

  Z: (10000, 30) PCA cum EV: 0.9867060098331422
  Active components: 78 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  29    0.037039   370.778165
1  52    0.033080   332.758830
2  63    0.032798   331.682514
3  21    0.031553   315.343221
4  46    0.029941   300.567249

Scoring ns_lion_650 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_650
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 128.7604217529297 occ_tpr: 0.999999689151476

  Z: (10000, 30) PCA cum EV: 0.9935582844773307
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.722663
1  1    0.012669   125.713758
2  2    0.012667   125.704177
3  3    0.012664   125.694581
4  4    0.012662   125.684908

Scoring ns_lion_780 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_780
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : sheep idx: 42 occ_tlog: 5.553964614868164 occ_tpr: 0.3157559109754578

  Z: (10000, 30) PCA cum EV: 0.9761138496105559
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  37    0.038013   380.976380
1  20    0.037449   374.499961
2  66    0.026897   271.816869
3  51    0.023231   233.231793
4   7    0.020156   200.700040

Scoring ns_lion_780 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_780
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 127.51744079589844 occ_tpr: 0.9999719049449961

  Z: (10000, 30) PCA cum EV: 0.9958323621103773
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.725140
1  1    0.012669   125.715388
2  2    0.012667   125.706016
3  3    0.012664   125.696827
4  4    0.012662   125.686784

Scoring ns_lion_801 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_801
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : coyote idx: 14 occ_tlog: 4.8347063064575195 occ_tpr: 0.22718801082016732

  Z: (10000, 30) PCA cum EV: 0.9970811139064608
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   3    0.059594   595.185791
1  52    0.053368   538.054468
2  36    0.043397   435.317872
3  24    0.038482   385.031390
4  41    0.032923   330.407587

Scoring ns_lion_801 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: ns_lion_801
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 132.88319396972656 occ_tpr: 0.9999999990344219

  Z: (10000, 30) PCA cum EV: 0.9999903381469153
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.013449   133.500137
1  2    0.013443   133.474202
2  3    0.013441   133.461015
3  4    0.013438   133.447646
4  5    0.013435   133.434090

Scoring s_bird_111 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_111
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : bird idx: 5 occ_tlog: 7.462847709655762 occ_tpr: 0.6522574389430714

  Z: (10000, 30) PCA cum EV: 0.9754764353274368
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  57    0.027119   272.998647
1  42    0.023948   239.958262
2  14    0.023311   232.498910
3  59    0.017860   179.583407
4  48    0.017910   179.456889

Scoring s_bird_111 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_111
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 151.66868591308594 occ_tpr: 0.9999999999989977

  Z: (10000, 30) PCA cum EV: 0.9991958737045934
  Active components: 10 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  1    0.100586  1004.864526
1  0    0.100510  1004.274398
2  2    0.100367  1003.078298
3  3    0.100339  1002.823354
4  4    0.100205  1001.716676

Scoring s_bird_117 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_117
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : bird idx: 5 occ_tlog: 3.878652572631836 occ_tpr: 0.2200893883927356

  Z: (10000, 30) PCA cum EV: 0.9782241036300547
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  44    0.066748   671.082963
1   6    0.035641   355.778872
2  12    0.029189   291.258121
3  52    0.028897   290.577650
4  31    0.027243   272.489041

Scoring s_bird_117 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_117
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 146.655517578125 occ_tpr: 0.9999999991667012

  Z: (10000, 30) PCA cum EV: 0.9985713916976238
  Active components: 7 / 80

/data/storage-occ-v2/repos/monte-carlo-selection/.venv/lib/python3.10/site-packages/sklearn/mixture/_base.py:275: ConvergenceWarning: Best performing initialization did not converge. Try different init parameters, or increase max_iter, tol, or check for degenerate data.
  warnings.warn(

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  2    0.000100  4648.029149
1  5    0.000100  2964.313969
2  0    0.000101  1028.917214
3  1    0.000101   906.445693
4  4    0.000103   380.771910

Scoring s_bird_132 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_132
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : hawk idx: 28 occ_tlog: 5.6682658195495605 occ_tpr: 0.3859120698286119

  Z: (10000, 30) PCA cum EV: 0.9703251693863422
  Active components: 77 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   9    0.048186   481.371196
1  67    0.042917   434.474002
2  79    0.041391   425.231799
3  41    0.033280   333.736713
4  50    0.029567   296.985123

Scoring s_bird_132 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_132
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 139.91136169433594 occ_tpr: 0.999999995017822

  Z: (10000, 30) PCA cum EV: 0.9984795297423261
  Active components: 17 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.059202   591.078133
1  1    0.059177   590.888471
2  2    0.059150   590.686231
3  3    0.059121   590.469622
4  4    0.059090   590.236440

Scoring s_bird_136 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_136
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : hawk idx: 28 occ_tlog: 6.44486665725708 occ_tpr: 0.49802725671982656

  Z: (10000, 30) PCA cum EV: 0.9795992551371455
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  35    0.039504   395.968324
1   6    0.028826   287.488579
2  70    0.027761   281.430148
3  68    0.027306   276.391721
4   8    0.023619   235.417879

Scoring s_bird_136 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_136
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 130.78858947753906 occ_tpr: 0.9999977738177014

  Z: (10000, 30) PCA cum EV: 0.9942656317434739
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.720414
1  1    0.012668   125.711695
2  2    0.012666   125.701696
3  3    0.012664   125.692046
4  4    0.012662   125.682620

Scoring s_bird_137 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_137
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : hawk idx: 28 occ_tlog: 4.692905426025391 occ_tpr: 0.2355624632512286

  Z: (10000, 30) PCA cum EV: 0.9833368099061772
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  22    0.035056   350.501153
1  78    0.032904   336.687772
2   1    0.019276   191.794112
3   3    0.019268   191.754186
4   7    0.019251   191.670967

Scoring s_bird_137 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_137
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 134.09031677246094 occ_tpr: 0.999999764979131

  Z: (10000, 30) PCA cum EV: 0.9939715146902017
  Active components: 9 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.111783  1116.794612
1  5    0.111469  1114.052365
2  1    0.111451  1114.046595
3  2    0.111393  1113.543916
4  3    0.111284  1112.613058

Scoring s_bird_212 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_212
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : hawk idx: 28 occ_tlog: 3.6383793354034424 occ_tpr: 0.1505279779704893

  Z: (10000, 30) PCA cum EV: 0.9877435936941765
  Active components: 74 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  37    0.135459  1360.977575
1   2    0.111286  1112.212268
2  55    0.065737   663.761257
3  43    0.065671   660.311780
4   6    0.059907   598.531001

Scoring s_bird_212 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_212
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 140.45724487304688 occ_tpr: 0.9999999999419584

  Z: (10000, 30) PCA cum EV: 0.992457742249826
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.723012
1  1    0.012669   125.713439
2  2    0.012667   125.704270
3  3    0.012664   125.694411
4  4    0.012662   125.684781

Scoring s_bird_350 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_350
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dolphin idx: 18 occ_tlog: 4.629918575286865 occ_tpr: 0.2900585669248048

  Z: (10000, 30) PCA cum EV: 0.9889971408119891
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  47    0.023582   236.548951
1   1    0.022459   223.638020
2   4    0.022443   223.542384
3  11    0.022401   223.302891
4  20    0.022341   222.957260

Scoring s_bird_350 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_bird_350
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 150.2509002685547 occ_tpr: 0.9999999998499476

  Z: (10000, 30) PCA cum EV: 0.9848505250993185
  Active components: 75 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  55    0.099316  1001.324410
1  46    0.083629   841.044030
2  21    0.066643   667.128784
3   1    0.064569   644.793103
4  73    0.054417   554.232743

Scoring s_butterfly_11 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_11
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : butterfly idx: 8 occ_tlog: 6.7041802406311035 occ_tpr: 0.7819326583899199

  Z: (10000, 30) PCA cum EV: 0.9848537090001628
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   4    0.017104   170.125430
1  20    0.017053   169.941357
2  26    0.017030   169.858374
3  63    0.015502   155.972922
4  64    0.015494   155.972555

Scoring s_butterfly_11 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_11
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 133.3912353515625 occ_tpr: 0.9999999999989999

  Z: (10000, 30) PCA cum EV: 0.9956693125423044
  Active components: 77 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.016118   160.196943
1  2    0.016112   160.167341
2  3    0.016109   160.152293
3  4    0.016105   160.136994
4  5    0.016102   160.121436

Scoring s_butterfly_144 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_144
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : bug idx: 6 occ_tlog: 5.9998979568481445 occ_tpr: 0.3235673594386347

  Z: (10000, 30) PCA cum EV: 0.9846283926744945
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   0    0.062048   619.528777
1  42    0.054721   549.730616
2  54    0.022999   231.253058
3   2    0.023156   230.636898
4  17    0.020989   209.441431

Scoring s_butterfly_144 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_144
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 125.76541137695312 occ_tpr: 0.9999999998400761

  Z: (10000, 30) PCA cum EV: 0.996173754814663
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012672   125.728776
1  1    0.012669   125.719349
2  2    0.012667   125.709721
3  3    0.012665   125.700212
4  4    0.012662   125.690511

Scoring s_butterfly_350 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_350
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : butterfly idx: 8 occ_tlog: 9.747540473937988 occ_tpr: 0.9564593750746426

  Z: (10000, 30) PCA cum EV: 0.9959828005085001
  Active components: 68 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.015914   158.134641
1  1    0.015912   158.128656
2  2    0.015909   158.115198
3  4    0.015903   158.087225
4  5    0.015900   158.073218

Scoring s_butterfly_350 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_350
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 117.89753723144531 occ_tpr: 0.9999999992411379

  Z: (10000, 30) PCA cum EV: 0.9972972142422805
  Active components: 23 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.043787   436.930539
1  1    0.043782   436.879124
2  2    0.043756   436.714282
3  3    0.043744   436.627181
4  4    0.043722   436.479330

Scoring s_butterfly_560 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_560
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : lobster idx: 31 occ_tlog: 5.004127502441406 occ_tpr: 0.3314310799713372

  Z: (10000, 30) PCA cum EV: 0.996932756548631
  Active components: 76 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  29    0.023497   706.346358
1  70    0.052156   491.480764
2  43    0.013710   453.194503
3   6    0.013304   439.119535
4  48    0.012774   424.233759

Scoring s_butterfly_560 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_butterfly_560
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 136.30899047851562 occ_tpr: 0.9999999999942395

  Z: (10000, 30) PCA cum EV: 0.9906403116183355
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   0    0.012649   125.798320
1   4    0.012662   125.678263
2   3    0.012668   125.674483
3   1    0.012677   125.674243
4  13    0.012617   125.673359

Scoring s_fish_350 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_350
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : fish idx: 22 occ_tlog: 4.971797466278076 occ_tpr: 0.3752792717105047

  Z: (10000, 30) PCA cum EV: 0.977143464027904
  Active components: 79 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  58    0.130552  1318.681686
1   1    0.072836   727.504583
2  41    0.070232   705.606920
3   7    0.053984   539.307985
4  36    0.045719   458.528546

Scoring s_fish_350 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_350
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 133.57334899902344 occ_tpr: 0.9999999999966345

  Z: (10000, 30) PCA cum EV: 0.9934285724302754
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  72    0.047444   481.731576
1  38    0.035164   352.463667
2  51    0.034922   351.044947
3  22    0.033113   331.007198
4  69    0.031371   317.433518

Scoring s_fish_4 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_4
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : fish idx: 22 occ_tlog: 4.834914207458496 occ_tpr: 0.3249109004063433

  Z: (10000, 30) PCA cum EV: 0.9770226620021276
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  60    0.037076   373.915810
1  30    0.033939   339.749059
2   6    0.033486   334.099455
3  27    0.032850   328.647724
4   2    0.030271   301.803649

Scoring s_fish_4 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_4
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 132.666748046875 occ_tpr: 0.9999999999989757

  Z: (10000, 30) PCA cum EV: 0.9917474830581341
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012672   125.728375
1  1    0.012669   125.718963
2  2    0.012667   125.709654
3  3    0.012665   125.700203
4  4    0.012662   125.690145

Scoring s_fish_500 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_500
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : squirrel idx: 46 occ_tlog: 4.948481559753418 occ_tpr: 0.5054363671217731

  Z: (10000, 30) PCA cum EV: 0.9829169809818268
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012673   125.734812
1  1    0.012670   125.726575
2  2    0.012668   125.716951
3  3    0.012665   125.707093
4  4    0.012663   125.696778

Scoring s_fish_500 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_500
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 117.60389709472656 occ_tpr: 0.9999997613270578

  Z: (10000, 30) PCA cum EV: 0.9937467831769027
  Active components: 78 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   0    0.183900  1838.185356
1  60    0.065633   664.522951
2   5    0.046053   459.864226
3  78    0.026284   271.799117
4  22    0.026513   265.009487

Scoring s_fish_600 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_600
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : fish idx: 22 occ_tlog: 4.1720356941223145 occ_tpr: 0.22340742503719896

  Z: (10000, 30) PCA cum EV: 0.9865027838095557
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   1    0.032651   325.578632
1   6    0.032605   325.292237
2  12    0.032540   324.867746
3  18    0.032480   324.507052
4  42    0.032126   322.295704

Scoring s_fish_600 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_600
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 107.08808135986328 occ_tpr: 0.999902191774357

  Z: (10000, 30) PCA cum EV: 0.9997206988336984
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012670   125.713426
1  1    0.012668   125.704236
2  2    0.012666   125.694929
3  3    0.012663   125.685502
4  4    0.012661   125.675951

Scoring s_fish_700 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_700
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : goose idx: 27 occ_tlog: 4.675352573394775 occ_tpr: 0.23164324005664813

  Z: (10000, 30) PCA cum EV: 0.9782167291268706
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   5    0.055791   557.281688
1  55    0.047890   482.665798
2  36    0.035139   352.243597
3   3    0.032082   319.991971
4  72    0.025233   256.751886

Scoring s_fish_700 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_700
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 142.61959838867188 occ_tpr: 0.9999999999989992

  Z: (10000, 30) PCA cum EV: 0.999608678099321
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012670   125.713394
1  1    0.012668   125.704204
2  2    0.012666   125.694897
3  3    0.012663   125.685470
4  4    0.012661   125.675919

Scoring s_fish_800 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_800
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : fish idx: 22 occ_tlog: 4.108976364135742 occ_tpr: 0.18240269252382346

  Z: (10000, 30) PCA cum EV: 0.9748289565322921
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   3    0.024945   248.556110
1  31    0.024720   247.201574
2  35    0.024678   246.946160
3   5    0.022799   227.127820
4  21    0.022720   226.777936

Scoring s_fish_800 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_800
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 135.54974365234375 occ_tpr: 0.9999999999971545

  Z: (10000, 30) PCA cum EV: 0.9933345366152935
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012671   125.721560
1  1    0.012668   125.712151
2  2    0.012666   125.702961
3  3    0.012664   125.692967
4  4    0.012662   125.682836

Scoring s_fish_900 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_900
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : turkey idx: 49 occ_tlog: 2.9279708862304688 occ_tpr: 0.11083530381713559

  Z: (10000, 30) PCA cum EV: 0.9859495362616144
  Active components: 37 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  72    0.029086  3376.778417
1  17    0.225375  1521.537707
2   0    0.186896  1258.802664
3   9    0.063912   430.505439
4  47    0.055631   377.917962

Scoring s_fish_900 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_fish_900
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 126.57810974121094 occ_tpr: 0.9999998270482985

  Z: (10000, 30) PCA cum EV: 0.998210923789884
  Active components: 48 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.021043   209.450672
1  1    0.021038   209.426274
2  2    0.021034   209.401347
3  3    0.021029   209.375872
4  4    0.021024   209.349819

Scoring s_oyster_350 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_oyster_350
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : oyster idx: 36 occ_tlog: 6.502268314361572 occ_tpr: 0.6022252333357273

  Z: (10000, 30) PCA cum EV: 0.9897991304460447
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0   3    0.019538   194.459972
1  11    0.019506   194.307383
2  13    0.019497   194.266472
3  18    0.019474   194.158520
4  19    0.019469   194.135775

Scoring s_oyster_350 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_oyster_350
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 104.49324035644531 occ_tpr: 0.9985748539198123

  Z: (10000, 30) PCA cum EV: 0.9972123211991857
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012673   125.742549
1  2    0.012669   125.725791
2  1    0.012669   125.721192
3  3    0.012666   125.710548
4  4    0.012664   125.705100

Scoring s_oyster_4 | resnet50_geirhos_tl:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_oyster_4
  source model      : resnet50_geirhos_tl
  eval model        : resnet50_geirhos_tl
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : oyster idx: 36 occ_tlog: 7.0787577629089355 occ_tpr: 0.7758986926418949

  Z: (10000, 30) PCA cum EV: 0.9771893195575103
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
    k  mix_weight  mass_debias
0  45    0.078020   784.173189
1  70    0.047611   483.407752
2  29    0.032102   321.248313
3   8    0.027060   269.585693
4  42    0.025165   252.161001

Scoring s_oyster_4 | resnet50_tl_20250829:   0%|          | 0/2000 [00:00<?, ?it/s]

CASE: s_oyster_4
  source model      : resnet50_tl_20250829
  eval model        : resnet50_tl_20250829
  occluder size     : 8
  Eligible          : 10000 / 10000
  Target            : dog idx: 17 occ_tlog: 117.82538604736328 occ_tpr: 0.9999999999113212

  Z: (10000, 30) PCA cum EV: 0.9880393627099693
  Active components: 80 / 80

fill metrics:   0%|          | 0/67 [00:00<?, ?it/s]

  Top-5 clusters by mass_debias:
   k  mix_weight  mass_debias
0  0    0.012672   125.734717
1  1    0.012670   125.725288
2  2    0.012668   125.715560
3  3    0.012665   125.705892
4  4    0.012663   125.696126

Done. Newly exported BGMM JSONLs for runs: 52
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_geirhos_tl/size_8/ns_elephant_780
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_tl_20250829/size_8/ns_elephant_780
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_geirhos_tl/size_8/ns_lion_350
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_tl_20250829/size_8/ns_lion_350
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_geirhos_tl/size_8/ns_lion_560
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_tl_20250829/size_8/ns_lion_560
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_geirhos_tl/size_8/ns_lion_650
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_tl_20250829/size_8/ns_lion_650
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_geirhos_tl/size_8/ns_lion_780
   /data/storage-occ-v2/repos/monte-carlo-selection/results/occlusion/bgmm_generated_size16_both_models/source_resnet50_tl_20250829/size_8/ns_lion_780
  ...

Skipped already processed runs: 27
   ns_cow_202 | resnet50_geirhos_tl | size 8
   ns_cow_202 | resnet50_tl_20250829 | size 8
   ns_cow_205 | resnet50_geirhos_tl | size 8
   ns_cow_205 | resnet50_tl_20250829 | size 8
   ns_cow_350 | resnet50_geirhos_tl | size 8
   ns_cow_350 | resnet50_tl_20250829 | size 8
   ns_cow_510 | resnet50_geirhos_tl | size 8
   ns_cow_510 | resnet50_tl_20250829 | size 8
   ns_cow_780 | resnet50_geirhos_tl | size 8
   ns_cow_780 | resnet50_tl_20250829 | size 8
  ...